### ISSUE TITLE
Opening remoteplay login URL on Raspberry Pi causes playactor to exit unexpectedly

### ISSUE THREAD

**Issue by BriskFrost** [dhleong/playactor#28]
Hello!

I am attempting to set up Playactor on a Raspberry Pi 4 running 64-bit Raspberry Pi OS. I can install Playactor, but can't login. 

When I run the `playactor login` command and "hit Enter to continue," it opens the browser to sign into the PSN and the command ends. When I get the redirect link and paste it into Terminal, I get the result `bash: <redirect-link>: No such file or directory` since the terminal is seeing it as a new command. I tried rebooting the device, updating NPM, and reinstalling Playactor but the issue persists.

`pi@STPi:~ $ sudo playactor login`
`In a moment, we will attempt to open a browser window for you to login to your PSN account.
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.
Hit ENTER to continue`
`pi@STPi:~ $ https://remoteplay.dl.playstation.net/remoteplay/redirect?code=<REDACTED>&cid=dc5ad5c1-46ec-4fb6-b61b-85b4fd70530e`
`[1] 3868`
`pi@STPi:~ $ -bash: https://remoteplay.dl.playstation.net/remoteplay/redirect?code=<REDACTED>: No such file or directory`
`pi@STPi:~ $`

Playactor's login function works fine on my MBP running macOS 11.2.3. After running the `playactor login` command and hitting Enter to continue, it opened the browser to sign into the PSN and waited with `URL>` in terminal. 

`sterling@Sterlings-MBP ~ % playactor login`
`In a moment, we will attempt to open a browser window for you to login to your PSN account.
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.
Hit ENTER to continue`
`URL> https://remoteplay.dl.playstation.net/remoteplay/redirect?code=<REDACTED>&cid=dc5ad5c1-46ec-4fb6-b61b-85b4fd70530e`
`Registering with device via Remote Play.`
`Go to Settings > System > Remote Play > Link Device`

Any ideas why this is happening? At this point I don't believe it's user error since I having it working correctly on my Mac, but maybe there are some other variables I'm missing on the Pi. Maybe an issue with 64-bit Raspberry Pi OS?

Thanks!

**Comment by dhleong** [comment]
Two thoughts:


   1. Don’t use `sudo` to run playactor. This is unlikely to fix anything,
   but at best it’s unnecessary, and at worst it has historically caused
   problems for users.
   2. Try adding the `--debug` flag; maybe it’ll give us an error to help
   debug.


What’s happening is, as you mentioned, the `playactor` command is exiting
unexpectedly, so because it’s not running, it cannot accept the URL you’re
pasting—bash is just trying to run the URL like a command, which of course
doesn’t work.

It’s unclear just from looking at it *why* playactor is exiting (especially
since the URL opens properly) and I don’t have a Raspberry Pi to test
against, but hopefully the `--debug` flag will help.

By the way, you should be careful with what you paste into an online form.
I’ve redacted it now and removed the history, but the `code` in the URLs
you pasted could be stolen by a bad actor to potentially hijack your
account. If anyone else is getting emails with each issue like I am, they
may also have the code in their email.

You may want to change your password, just in case.

**Comment by BriskFrost** [comment]
Thanks for catching the codes from the URLs I pasted; I appreciate it. I meant to double back and remove the links, but I forgot to. 

I did run into this issue while running the command without `sudo` as well. The attempt with `sudo` just happened to the most recent attempt. I'll definitely keep in mind not to use it on future attempts.

Here are the results for running the login command with the `--debug` flag. Nothing really stands out to me, but hopefully something catches your eye.

```
pi@STPi:~ $ playactor login --debug
  playactor:cli:options findDevice with: DeviceOptions {
  enableDebug: true,
  machineFriendly: false,
  searchTimeout: 30000,
  connectTimeout: 15000,
  dontAuthenticate: false,
  alwaysAuthenticate: false,
  deviceOnlyPS4: false,
  deviceOnlyPS5: false,
  localBindAddress: undefined,
  localBindPort: undefined,
  credentialsPath: undefined,
  passCode: undefined,
  deviceIp: undefined,
  deviceHostName: undefined,
  deviceHostId: undefined
} +0ms
  playactor:discovery discover( { pingIntervalMillis: 5000, timeoutMillis: 30000, uniqueDevices: true } ) +0ms
  playactor:discovery:udp acquire @ 0 +0ms
  playactor:discovery:udp created new socket for  { localBindAddress: undefined, localBindPort: undefined } +1ms
  playactor:discovery:udp acquire @ 0 +2ms
  playactor:discovery:udp joining existing socket for  { localBindAddress: undefined, localBindPort: undefined } +0ms
  playactor:discovery:udp send: 53524348202a20485454502f312e310a6465766963652d646973636f766572792d70726f746f636f6c2d76657273696f6e3a30303032303032300a  to  255.255.255.255 : 987 +2ms
  playactor:discovery:udp send: 53524348202a20485454502f312e310a6465766963652d646973636f766572792d70726f746f636f6c2d76657273696f6e3a30303033303031300a  to  255.255.255.255 : 9302 +1ms
  playactor:discovery:udp listening on  { address: '0.0.0.0', family: 'IPv4', port: 37730 } +6ms
  playactor:discovery:messages parse: HTTP/1.1 200 Ok
host-id:<REDACTED>
host-type:PS5
host-name:Sterling's PS5
host-request-port:997
device-discovery-protocol-version:00030010
system-version:08540001
 +0ms
  playactor:discovery:udp received device: {
  type: 'DEVICE',
  sender: { address: '10.7.17.20', family: 'IPv4', port: 9302, size: 165 },
  version: '00020020',
  data: {
    type: 'DEVICE',
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE',
    'host-id': '<REDACTED>',
    'host-type': 'PS5',
    'host-name': "Sterling's PS5",
    'host-request-port': '997',
    'device-discovery-protocol-version': '00030010',
    'system-version': '08540001'
  }
} +107ms
  playactor:discovery:messages parse: HTTP/1.1 200 Ok
host-id:<REDACTED>
host-type:PS5
host-name:Sterling's PS5
host-request-port:997
device-discovery-protocol-version:00030010
system-version:08540001
 +3ms
  playactor:discovery:udp received device: {
  type: 'DEVICE',
  sender: { address: '10.7.17.20', family: 'IPv4', port: 9302, size: 165 },
  version: '00030010',
  data: {
    type: 'DEVICE',
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE',
    'host-id': '<REDACTED>',
    'host-type': 'PS5',
    'host-name': "Sterling's PS5",
    'host-request-port': '997',
    'device-discovery-protocol-version': '00030010',
    'system-version': '08540001'
  }
} +3ms
  playactor:discovery:udp closing udp network +3ms
  playactor:discovery:udp release @ 0 +0ms
  playactor:discovery:udp closing udp network +0ms
  playactor:discovery:udp release @ 0 +1ms
  playactor:waker device {
  address: { address: '10.7.17.20', family: 'IPv4', port: 9302, size: 165 },
  hostRequestPort: 997,
  extras: {
    statusLine: '200 Ok',
    statusCode: '200',
    statusMessage: 'Ok',
    status: 'AWAKE'
  },
  discoveryVersion: '00030010',
  systemVersion: '08540001',
  id: '<REDACTED>',
  name: "Sterling's PS5",
  status: 'AWAKE',
  type: 'PS5'
} is already awake +0ms
  playactor:credentials:disk reading credentials at /home/pi/.config/playactor/credentials.json +0ms
In a moment, we will attempt to open a browser window for you to login to your PSN account.
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.
Hit ENTER to continue
pi@STPi:~ $ 
```

**Comment by NikDevx** [comment]
You need to login with homebridge user and login without sudo.

`homebridge@raspberrypi: playactor login`

**Comment by Pustur** [comment]
@dhleong Just a warning that I can still see the codes in your reply. Since you replied via email, there's a button `[…]` that when clicked still shows the original message from @BriskFrost.

I don't know if you can update that as well

**Comment by dhleong** [comment]
Removed, thanks for the heads up.

> Oh, I almost forgot, I can also see the edit history in the original post

The old revisions should be deleted, so you shouldn't be able to see them?

**Comment by Pustur** [comment]
> The old revisions should be deleted, so you shouldn't be able to see them?

Oh yeah sorry I misread that, sorry.

**Comment by dhleong** [comment]
Hello! Sorry it's been so long, but I just published version 0.3.0 which adds a `--no-open-urls` flag, which will disable the URL opening. I *suspect* that something is going wrong in that process, and this is an escape hatch which *may* help you out.

**Comment by BriskFrost** [comment]
That worked perfectly! Unfortunately, I'm now running into another roadblock. After entering the code from the "Link Device" screen on my PS5, I'm presented with the following result:
```
SyntaxError: Cannot convert 0x to a BigInt
    at BigInt (<anonymous>)
    at registKeyToCredential (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
    at OauthCredentialRequester.<anonymous> (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```
I'm not sure if this matters, but my PSN account does have 2FA enabled. Not sure if that could be conflicting with something. 

Also, I noticed you automatically redacted some command results and added verbiage encouraging people to use caution when copying results. Thank you for taking measures to help protect people's privacy. I'm glad to see something good might have come from my momentary lapse in judgment.

**Comment by Rocknpools** [comment]
> That worked perfectly! Unfortunately, I'm now running into another roadblock. After entering the code from the "Link Device" screen on my PS5, I'm presented with the following result:
> 
> ```
> SyntaxError: Cannot convert 0x to a BigInt
>     at BigInt (<anonymous>)
>     at registKeyToCredential (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
>     at OauthCredentialRequester.<anonymous> (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)
> ```
> 
> I'm not sure if this matters, but my PSN account does have 2FA enabled. Not sure if that could be conflicting with something.
> 
> Also, I noticed you automatically redacted some command results and added verbiage encouraging people to use caution when copying results. Thank you for taking measures to help protect people's privacy. I'm glad to see something good might have come from my momentary lapse in judgment.

I get the same error! and I'm running playactor too from a raspberry

**Comment by NikDevx** [comment]
The same error!

> SyntaxError: Cannot convert 0x to a BigInt
>     at BigInt (<anonymous>)
>     at registKeyToCredential (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:44:22)
>     at OauthCredentialRequester.<anonymous> (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:66:32)
>     at Generator.next (<anonymous>)
>     at fulfilled (/usr/lib/node_modules/playactor/dist/credentials/oauth/requester.js:5:58)
>     at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by NikDevx** [comment]
With v 0.2.3 working fine.

> Also, I noticed you automatically redacted some command results and added verbiage encouraging people to use caution when copying results. Thank you for taking measures to help protect people's privacy. I'm glad to see something good might have come from my momentary lapse in judgment.

**Comment by Rocknpools** [comment]
Any news on this side?

**Comment by dhleong** [comment]
I haven't had a chance to test it, but I've just released 0.3.2 which I *believe* should fix this—if `0.3.0` works but `0.3.1` did not, `0.3.2` should be fixed. Basically the stuff I added to redact log data may have munged important data before it got sent over the wire (or, perhaps, before being parsed).

Let me know if it helps, and feel free to open a new issue if something else pops up!

**Comment by BriskFrost** [comment]
This worked for me!

As a note, I can't confirm 100%, but I think some of my previous issues could have stemmed from having Pi Hole running on my raspberry pi. I just happen to uninstall, but if similar issues arise for Pi users, it might be something to have the user check first as running Pi Hole is pretty common.

Thanks again for all your help!

**Comment by Rocknpools** [comment]
Updating to 0.3.2 worked for me to
