### ISSUE TITLE
Raspberry Pi

### ISSUE THREAD

**Issue by duckdany** [dhleong/playactor#35]
Hello!

How can I login on PS5 with Raspberry Pi?
```
In a moment, we will attempt to open a browser window for you to login to your PSN account.
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.
Hit ENTER to continue
```
I hit the enter and nothing happens because there is no gui on raspberry pi. I use my pi with ssh from my Mac.
So how can I login?

Thank you!

**Comment by dhleong** [comment]
Try the `--no-open-urls` flag

**Comment by duckdany** [comment]
> Try the `--no-open-urls` flag

No it's working with this flag. But I tried it 2 months ago and I couldn't login with this flag. I don't know what happened. Thank you

**Comment by tommyMX** [comment]
after Enter the pin I got this error:

Error: Registration error: 403: Forbidden: Other Error
    at Object.<anonymous> (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:88:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
