### ISSUE TITLE
Registration error (PS5)

### ISSUE THREAD

**Issue by nseries100** [dhleong/playactor#38]
EDIT: Probably same as #21 

Playactor - installed via homebridge terminal
Device - only one PS5

PS5 is reachable and awake:
homebridge@raspberrypi:/var/lib/homebridge $ playactor browse
{
  "address": {
    "address": "192.168.1.35",
    "family": "IPv4",
    "port": 9302,
    "size": 154
  },
  "hostRequestPort": 997,
  "extras": {
    "statusLine": "200 Ok",
    "statusCode": "200",
    "statusMessage": "Ok",
    "status": "AWAKE"
  },
  "discoveryVersion": "00030010",
  "systemVersion": "09090001",
  "id": "00E4210B04BE",
  "name": "PS5",
  "status": "AWAKE",
  "type": "PS5"
}

Im trying to register my PS5 and Im getting this Error:

homebridge@raspberrypi:/var/lib/homebridge $ playactor login --no-open-urls
Open the following URL in a web browser to login to your PSN account.
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.
  ***URL***
These URLs may contain sensitive information; if sharing debug logs anywhere, PLEASE make sure to redact them first!
URL> ***PASTED-URL***
Registering with device via Remote Play.
Go to Settings > System > Remote Play > Link Device
Enter PIN here> ***PIN***
Error: Registration error: 403: Forbidden: Other Error
    at Object.<anonymous> (/usr/lib/node_modules/playactor/dist/remoteplay/protocol.js:88:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/playactor/dist/remoteplay/protocol.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

After that I cant run command playactor login --no-open-urls again. I get error: 
homebridge@raspberrypi:/var/lib/homebridge $ playactor login --no-open-urls
Error: Registration error: 403: Forbidden: Other Error
    at Object.<anonymous> (/usr/lib/node_modules/playactor/dist/remoteplay/protocol.js:88:19)
    at Generator.next (<anonymous>)
    at fulfilled (/usr/lib/node_modules/playactor/dist/remoteplay/protocol.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

Any ideas?

**Comment by dhleong** [comment]
Looks like #21 to me. Going to go ahead and close this one; if you uncover any helpful new information please post it on #21; if you find any evidence that this is a separate issue, feel free to comment here again and I'll reopen!
