### ISSUE TITLE
no browser to login

### ISSUE THREAD

**Issue by tommyMX** [dhleong/playactor#40]
Hi, 
i am running playactor on a NAS in a docker with terminal. But I have no Browser there. How can I also login?

In a moment, we will attempt to open a browser window for you to login to your PSN account.                                                                       
When the page shows "redirect", copy the URL from your browser's address bar and paste it here.                                                                   
Hit ENTER to continue 

When I hit enter I am again in my terminal command line.

Thx

**Comment by dhleong** [comment]
See https://github.com/dhleong/playactor/issues/35
