### ISSUE TITLE
Eacces error when trying to link PS5

### ISSUE THREAD

**Issue by sterumbelow** [dhleong/playactor#51]
Hello, 

I've just got my PS5 set up and would like to add it to Homebridge/Home but I'm running into the problem below, immediately after entering the link code.

`Error: EACCES: permission denied, mkdir '/home/pi/.config/playactor'`

I've tried multiple times but I'm still running into the same problem. 

I've already got the PS5 into the Home app, which shows that the PS5 is on/off, but it doesn't turn on/off when clicked, presumably because it isn't actually linked through Remote Play.

I've tried various commands to fix this but haven't found one that's worked. 

Thanks for your help, 
Ste.

**Comment by dhleong** [comment]
This is not a help forum for homebridge or homebridge integrations, but my guess is homebridge is running as a different user than you created the config with (and/or you haven't performed initial config) so it can't read it. It looks like [the homebridge project](https://github.com/kopiro/homebridge-playstation) has some documentation on the correct way to setup auth for use with it.
