### ISSUE TITLE
Install on ioBroker not possibl...ERROR: Process exited with code 25

### ISSUE THREAD

**Issue by ghost** [dhleong/playactor#65]
host.MeleMiniPC Cannot install dhleong/playactor#bf16993fd15b2e1ee64b7f90d37138ca057c61dc: 0

ERROR: Process exited with code 25

**Comment by SpeedyBlade** [comment]
i have the same issue...cant install playactor on iobroker

Node.js: v20.15.0
NPM: 10.7.0

**Comment by dhleong** [comment]
What is iobroker?

**Comment by SpeedyBlade** [comment]
smarthome broker...similar like homeassistant
check this out

https://www.iobroker.net/

**Comment by dhleong** [comment]
Looks cool! However, playactor is not designed for direct use by anything like that. You'll need to build an adapter, most likely. Unfortunately, I don't have the bandwidth these days to maintain that.

If someone else has already built an adapter, please raise this issue on their project, as I am unaffiliated and as such cannot provide help.
